#! /bin/bash
########################################################################
# Spine Console
########################################################################
#
# @fatherbrennan
#

# Codes
TEXT_RESET='\033[0m'
TEXT_BOLD='\033[1m'
TEXT_UNDERLINE='\033[4m'

# Get relative path
app="$(cd "$(dirname "${BASH_SOURCE[0]}")";pwd -P)/"

usage()
{
    echo "Usage: spine <command> <extension>"
}

# Exit if no args
[ -z "$1" ] && echo -e "Invalid command: <<Empty argument>>\n $(usage)" && exit 1

# Imports
source '.config'

# Return help
show_help()
{
    echo -e "${TEXT_BOLD}spine${TEXT_RESET}\n $(usage)\n\n${TEXT_UNDERLINE}commands${TEXT_RESET}\n\n ${TEXT_BOLD}start, dev${TEXT_RESET}\n\tbuild app assets in dev mode\n\n ${TEXT_BOLD}open${TEXT_RESET}\n\topen the app in the default web browser\n\n ${TEXT_BOLD}clear${TEXT_RESET}\n\tclear the framework cache including assets\n\n ${TEXT_BOLD}-h, --help${TEXT_RESET}\n\tdisplay command info\n\n${TEXT_UNDERLINE}extensions${TEXT_RESET}\n\n ${TEXT_BOLD}-s, --script${TEXT_RESET}\n\textends [ start ] [ dev ]\n\t  run config SCRIPT_TAIL after spine build process\n\n${TEXT_UNDERLINE}exmaples${TEXT_RESET}\n\n ${TEXT_BOLD}spine dev --script${TEXT_RESET}\n\trun dev build process and then run config defined script\n\twhere SCRIPT_TAIL=\"npm dev\". Can be used within framework\n\tenvironments such as the Electron framework\n\n ${TEXT_BOLD}spine open${TEXT_RESET}\n\topen the Public/index.html file using the machine's\n\tdefault web browser"
}

# Args
case $1 in
    dev | start)
        "${app}Framework/Scripts/dev.sh" "$app" && cont=true || cont=false
        if [ -n "$2" ] && [ "$cont" == "true" ]
        then
            case $2 in
                -s | --script) $SCRIPT_TAIL ;;
                *) echo "Warning: '${2}' is not a valid extension" ;;
            esac
        fi
    ;;
    open)
        # OS check
        a="$(uname -s)"
        b="$(pwd)"
        case "${a}"
            in
            Linux*)
                cmd='xdg-open'
            ;;
            Darwin*)
                cmd='open'
            ;;
            CYGWIN*)
                cmd='cmd.exe /C start'
            ;;
            MINGW*)
                cmd='start'
                b="$(pwd -W)"
            ;;
            *)
                echo "UNKNOWN MACHINE: ${a}"
        esac
        # Open homepage in default browser
        $cmd "file://${b}/Public/index.html"
    ;;
    clear)
        "${app}Framework/Scripts/cache_clear.sh" "$app"
    ;;
    -h | --help)
        show_help
    ;;
    *)
        echo -e "Invalid argument:\n $(usage)";exit 1
    ;;
esac